# url is currently only used only for the RSS feed in feed.xml
url: https://algoritando.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'algoritando/algoritando.github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-56084241-1'

# Set this to your disqus shortname to enable comments.
disqus: 'br-lemes'

permalink: /:year/:month/:title/
paginate: 5

exclude: ['README.md', 'LICENSE']

excerpt_separator: '<!-- more -->'

default_paneltype: success

defaults:
  -
    values:
      comments: true
      layout: post
      lang: pt-BR

plugins:
  - jekyll-paginate
  - jekyll-sitemap
